version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: dev
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
        - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: