version: '3'

services:
  db8:
    image: mysql:latest
    container_name: db8
    volumes:
      - db_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_USER: dev
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
        - "3306:3306"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db8

volumes:
  db_data: